import type { SubLesson } from "../../types";

export const subLesson_1_1: SubLesson = {
  slug: "1-1",
  title: "What is Sound",
  blurb: "Vibration, frequency, amplitude — the building blocks.",
  lessons: [
    {
      slug: "1-1-1",
      title: "Sound is Vibration",
      exercises: [
        {
          id: "1-1.1-1-1.q1",
          type: "concept-slide",
          prompt: "Sound is something shaking",
          visual: "vibrating-string",
          caption: "When something vibrates, it pushes air. That push reaches your ear as sound.",
        },
        {
          id: "1-1.1-1-1.q2",
          type: "tap-to-hear",
          prompt: "Hear a 440 Hz sine — a pure tone",
          patch: { waveform: "sine", filterFreq: 8000, attack: 0.05, release: 0.5, volume: 0.8 },
          notes: ["A4"],
          caption: "440 vibrations per second. That's the note A.",
        },
        {
          id: "1-1.1-1-1.q3",
          type: "ab-compare",
          prompt: "Pick the one that is sound",
          a: { patch: { volume: 0 }, notes: [], label: "Silence" },
          b: { patch: { waveform: "sine", filterFreq: 8000, volume: 0.8 }, notes: ["A4"], label: "Vibration" },
          correct: "b",
          explainer: "Silence = no vibration. Tone = vibration.",
        },
        {
          id: "1-1.1-1-1.q4",
          type: "multi-choice",
          prompt: "What makes sound?",
          question: "Sound happens when…",
          options: ["Light bounces off walls", "Something vibrates and pushes air", "Magnets line up", "Numbers add up"],
          correctIndex: 1,
        },
      ],
    },
    {
      slug: "1-1-2",
      title: "Frequency = Pitch",
      exercises: [
        {
          id: "1-1.1-1-2.q1",
          type: "concept-slide",
          prompt: "Faster = higher pitch",
          visual: "amplitude-vs-frequency",
          caption: "More wiggles per second = higher note. Frequency is measured in Hertz (Hz).",
        },
        {
          id: "1-1.1-1-2.q2",
          type: "ab-compare",
          prompt: "Which is higher?",
          a: { patch: { waveform: "sine", volume: 0.8 }, notes: ["A3"], label: "A" },
          b: { patch: { waveform: "sine", volume: 0.8 }, notes: ["A5"], label: "B" },
          correct: "b",
        },
        {
          id: "1-1.1-1-2.q3",
          type: "multi-choice",
          prompt: "Doubling the frequency…",
          question: "If you double the Hz, the note goes…",
          options: ["Lower", "Up an octave", "Quieter", "Stays the same"],
          correctIndex: 1,
          explainer: "Each octave = 2× the frequency.",
        },
        {
          id: "1-1.1-1-2.q4",
          type: "tap-to-hear",
          prompt: "Slow sweep, low to high",
          patch: { waveform: "sine", filterFreq: 8000, volume: 0.7 },
          notes: ["C3", "C4", "C5", "C6"],
        },
      ],
    },
    {
      slug: "1-1-3",
      title: "Amplitude = Loudness",
      exercises: [
        {
          id: "1-1.1-1-3.q1",
          type: "concept-slide",
          prompt: "Bigger wiggle = louder",
          visual: "amplitude-vs-frequency",
          caption: "Frequency and loudness are independent. A note can be high and quiet, or low and loud.",
        },
        {
          id: "1-1.1-1-3.q2",
          type: "ab-compare",
          prompt: "Pick the louder one",
          a: { patch: { waveform: "sine", volume: 0.2 }, notes: ["A4"], label: "A" },
          b: { patch: { waveform: "sine", volume: 0.9 }, notes: ["A4"], label: "B" },
          correct: "b",
        },
        {
          id: "1-1.1-1-3.q3",
          type: "knob-tweak",
          prompt: "Set volume to a moderate level",
          param: "volume",
          target: 0.7,
          tolerance: 0.08,
          initialPatch: { waveform: "sine", filterFreq: 8000, volume: 0.2 },
          previewNote: "A4",
        },
        {
          id: "1-1.1-1-3.q4",
          type: "multi-choice",
          prompt: "Loudness is…",
          question: "Volume controls…",
          options: ["Pitch", "Speed", "Amplitude", "Tone color"],
          correctIndex: 2,
        },
      ],
    },
    {
      slug: "1-1-4",
      title: "Timbre Tease",
      exercises: [
        {
          id: "1-1.1-1-4.q1",
          type: "ab-compare",
          prompt: "Same note. Same loudness. Different…?",
          a: { patch: { waveform: "sine", volume: 0.7 }, notes: ["A4"], label: "Sine" },
          b: { patch: { waveform: "sawtooth", volume: 0.7, filterFreq: 8000 }, notes: ["A4"], label: "Saw" },
          correct: "b",
          explainer: "Both are 'A4' at the same loudness. The difference is timbre — the shape of the wave.",
        },
        {
          id: "1-1.1-1-4.q2",
          type: "concept-slide",
          prompt: "Wave shape = tone color",
          visual: "waveform-morph",
          caption: "Different wave shapes have different harmonic content. We'll meet four of them next.",
        },
        {
          id: "1-1.1-1-4.q3",
          type: "multi-choice",
          prompt: "Two notes at the same pitch and loudness can still sound different. That's…",
          question: "The word for 'tone color':",
          options: ["Frequency", "Amplitude", "Timbre", "Octave"],
          correctIndex: 2,
        },
      ],
    },
  ],
};
