import type { SubLesson } from "../../types";

export const subLesson_1_3: SubLesson = {
  slug: "1-3",
  title: "Oscillator",
  blurb: "Sine, sawtooth, square, triangle — the four shapes.",
  lessons: [
    {
      slug: "1-3-1",
      title: "Sine = Pure",
      exercises: [
        { id: "1-3.1-3-1.q1", type: "concept-slide", prompt: "Sine wave",
          visual: "waveform-morph", caption: "The smoothest possible tone. One frequency, no extras." },
        { id: "1-3.1-3-1.q2", type: "tap-to-hear", prompt: "Hear a sine",
          patch: { waveform: "sine", filterFreq: 8000, volume: 0.8 }, notes: ["A4"] },
        { id: "1-3.1-3-1.q3", type: "waveform-pick", prompt: "Pick the sine",
          shape: "sine", options: ["sine", "square", "triangle", "sawtooth"] },
        { id: "1-3.1-3-1.q4", type: "multi-choice", prompt: "Sine sounds…",
          question: "Compared to other shapes, a sine is…",
          options: ["Pure / smooth", "Buzzy", "Hollow", "Sharp"], correctIndex: 0 },
      ],
    },
    {
      slug: "1-3-2",
      title: "Sawtooth = Bright",
      exercises: [
        { id: "1-3.1-3-2.q1", type: "concept-slide", prompt: "Sawtooth wave",
          visual: "waveform-morph", caption: "Buzzy. Lots of harmonics. Classic synth lead sound." },
        { id: "1-3.1-3-2.q2", type: "tap-to-hear", prompt: "Hear a saw",
          patch: { waveform: "sawtooth", filterFreq: 8000, volume: 0.8 }, notes: ["A4"] },
        { id: "1-3.1-3-2.q3", type: "ab-compare", prompt: "Which is the sawtooth?",
          a: { patch: { waveform: "sine", volume: 0.8 }, notes: ["A4"] },
          b: { patch: { waveform: "sawtooth", filterFreq: 8000, volume: 0.8 }, notes: ["A4"] },
          correct: "b" },
        { id: "1-3.1-3-2.q4", type: "waveform-pick", prompt: "Pick the saw",
          shape: "sawtooth", options: ["sine", "square", "triangle", "sawtooth"] },
      ],
    },
    {
      slug: "1-3-3",
      title: "Square = Hollow",
      exercises: [
        { id: "1-3.1-3-3.q1", type: "concept-slide", prompt: "Square wave",
          visual: "waveform-morph", caption: "Hollow, woody. Like a clarinet — odd harmonics only." },
        { id: "1-3.1-3-3.q2", type: "tap-to-hear", prompt: "Hear a square",
          patch: { waveform: "square", filterFreq: 8000, volume: 0.7 }, notes: ["A4"] },
        { id: "1-3.1-3-3.q3", type: "ab-compare", prompt: "Which is the square?",
          a: { patch: { waveform: "sawtooth", filterFreq: 8000, volume: 0.7 }, notes: ["A4"] },
          b: { patch: { waveform: "square", filterFreq: 8000, volume: 0.7 }, notes: ["A4"] },
          correct: "b" },
        { id: "1-3.1-3-3.q4", type: "waveform-pick", prompt: "Pick the square",
          shape: "square", options: ["sine", "square", "triangle", "sawtooth"] },
        { id: "1-3.1-3-3.q5", type: "multi-choice", prompt: "Square waves are…",
          question: "Which best describes square?",
          options: ["Buzzy", "Hollow", "Pure", "Smooth"], correctIndex: 1 },
      ],
    },
    {
      slug: "1-3-4",
      title: "Triangle = Mellow",
      exercises: [
        { id: "1-3.1-3-4.q1", type: "concept-slide", prompt: "Triangle wave",
          visual: "waveform-morph", caption: "Mellow. Like a softer square — fewer harmonics, gentler edge." },
        { id: "1-3.1-3-4.q2", type: "tap-to-hear", prompt: "Hear a triangle",
          patch: { waveform: "triangle", filterFreq: 8000, volume: 0.8 }, notes: ["A4"] },
        { id: "1-3.1-3-4.q3", type: "ab-compare", prompt: "Which is the triangle?",
          a: { patch: { waveform: "square", filterFreq: 8000, volume: 0.8 }, notes: ["A4"] },
          b: { patch: { waveform: "triangle", filterFreq: 8000, volume: 0.8 }, notes: ["A4"] },
          correct: "b" },
        { id: "1-3.1-3-4.q4", type: "waveform-pick", prompt: "Pick the triangle",
          shape: "triangle", options: ["sine", "square", "triangle", "sawtooth"] },
      ],
    },
    {
      slug: "1-3-5",
      title: "Pick the Wave",
      exercises: [
        { id: "1-3.1-3-5.q1", type: "waveform-pick", prompt: "Sine?",
          shape: "sine", options: ["sine", "square", "triangle", "sawtooth"] },
        { id: "1-3.1-3-5.q2", type: "waveform-pick", prompt: "Sawtooth?",
          shape: "sawtooth", options: ["sine", "square", "triangle", "sawtooth"] },
        { id: "1-3.1-3-5.q3", type: "waveform-pick", prompt: "Square?",
          shape: "square", options: ["sine", "square", "triangle", "sawtooth"] },
        { id: "1-3.1-3-5.q4", type: "ab-compare", prompt: "Which sounds buzziest?",
          a: { patch: { waveform: "sine", volume: 0.8 }, notes: ["A4"] },
          b: { patch: { waveform: "sawtooth", filterFreq: 8000, volume: 0.8 }, notes: ["A4"] },
          correct: "b" },
        { id: "1-3.1-3-5.q5", type: "multi-choice", prompt: "Which shape has the brightest sound?",
          question: "Brightest = most harmonic content =",
          options: ["Sine", "Triangle", "Square", "Sawtooth"], correctIndex: 3 },
      ],
    },
  ],
};
