import type { SubLesson } from "../../types";

export const subLesson_1_4: SubLesson = {
  slug: "1-4",
  title: "Amp Envelope",
  blurb: "Notes have a shape over time — attack and release.",
  lessons: [
    {
      slug: "1-4-1",
      title: "Notes Have Shape",
      exercises: [
        { id: "1-4.1-4-1.q1", type: "concept-slide", prompt: "Volume over time",
          visual: "envelope-shape", caption: "How a note rises in and fades out — the envelope." },
        { id: "1-4.1-4-1.q2", type: "ab-compare", prompt: "Pluck or pad?",
          a: { patch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.01, release: 0.2, volume: 0.8 }, notes: ["C4"], label: "Pluck" },
          b: { patch: { waveform: "triangle", filterFreq: 2000, attack: 1.5, release: 2.0, volume: 0.8 }, notes: ["C4"], label: "Pad" },
          correct: "a",
          explainer: "Pluck: fast attack, short release. Pad: slow attack, long release." },
        { id: "1-4.1-4-1.q3", type: "multi-choice", prompt: "Envelope controls…",
          question: "What does an amp envelope shape?",
          options: ["The pitch over time", "The loudness over time", "The waveform shape", "The reverb amount"],
          correctIndex: 1 },
      ],
    },
    {
      slug: "1-4-2",
      title: "Attack",
      exercises: [
        { id: "1-4.1-4-2.q1", type: "concept-slide", prompt: "Attack = how fast it rises",
          visual: "envelope-shape", caption: "Short attack = punchy. Long attack = swell." },
        { id: "1-4.1-4-2.q2", type: "ab-compare", prompt: "Which has a slow attack?",
          a: { patch: { waveform: "triangle", filterFreq: 4000, attack: 0.01, release: 0.4, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "triangle", filterFreq: 4000, attack: 1.5, release: 0.4, volume: 0.8 }, notes: ["C4"] },
          correct: "b" },
        { id: "1-4.1-4-2.q3", type: "knob-tweak", prompt: "Set a fast attack (0.01 s)",
          param: "attack", target: 0.01, tolerance: 0.05,
          initialPatch: { waveform: "sawtooth", filterFreq: 3000, attack: 1.0, release: 0.4, volume: 0.8 },
          previewNote: "C4" },
        { id: "1-4.1-4-2.q4", type: "knob-tweak", prompt: "Set a slow attack (~2 s)",
          param: "attack", target: 2.0, tolerance: 0.4,
          initialPatch: { waveform: "triangle", filterFreq: 2000, attack: 0.01, release: 1.0, volume: 0.8 },
          previewNote: "C4" },
      ],
    },
    {
      slug: "1-4-3",
      title: "Release",
      exercises: [
        { id: "1-4.1-4-3.q1", type: "concept-slide", prompt: "Release = how fast it fades",
          visual: "envelope-shape", caption: "Short release = staccato. Long release = trails." },
        { id: "1-4.1-4-3.q2", type: "ab-compare", prompt: "Which has a long release?",
          a: { patch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.05, release: 0.1, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.05, release: 2.5, volume: 0.8 }, notes: ["C4"] },
          correct: "b" },
        { id: "1-4.1-4-3.q3", type: "knob-tweak", prompt: "Set a short release (~0.1 s)",
          param: "release", target: 0.1, tolerance: 0.08,
          initialPatch: { waveform: "sawtooth", filterFreq: 3000, attack: 0.05, release: 1.5, volume: 0.8 },
          previewNote: "C4" },
        { id: "1-4.1-4-3.q4", type: "knob-tweak", prompt: "Set a long release (~2.5 s)",
          param: "release", target: 2.5, tolerance: 0.4,
          initialPatch: { waveform: "triangle", filterFreq: 2000, attack: 0.05, release: 0.2, volume: 0.8 },
          previewNote: "C4" },
      ],
    },
    {
      slug: "1-4-4",
      title: "Pluck vs Pad",
      exercises: [
        { id: "1-4.1-4-4.q1", type: "knob-tweak", prompt: "Make a pluck — short attack",
          param: "attack", target: 0.01, tolerance: 0.05,
          initialPatch: { waveform: "sawtooth", filterFreq: 3000, attack: 1.0, release: 0.4, volume: 0.8 },
          previewNote: "C4" },
        { id: "1-4.1-4-4.q2", type: "knob-tweak", prompt: "…and short release",
          param: "release", target: 0.2, tolerance: 0.1,
          initialPatch: { waveform: "sawtooth", filterFreq: 3000, attack: 0.01, release: 1.5, volume: 0.8 },
          previewNote: "C4" },
        { id: "1-4.1-4-4.q3", type: "ab-compare", prompt: "Which is the pluck?",
          a: { patch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.01, release: 0.2, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "triangle", filterFreq: 2000, attack: 1.5, release: 2.0, volume: 0.8 }, notes: ["C4"] },
          correct: "a" },
        { id: "1-4.1-4-4.q4", type: "multi-choice", prompt: "A pad is…",
          question: "A pad sound has…",
          options: ["Short attack and short release",
                    "Slow attack and long release",
                    "Slow attack and short release",
                    "Fast attack and long release"],
          correctIndex: 1 },
      ],
    },
    {
      slug: "1-4-5",
      title: "Envelope Ear",
      exercises: [
        { id: "1-4.1-4-5.q1", type: "ab-compare", prompt: "Which has a slower attack?",
          a: { patch: { waveform: "triangle", filterFreq: 3000, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "triangle", filterFreq: 3000, attack: 1.0, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          correct: "b" },
        { id: "1-4.1-4-5.q2", type: "ab-compare", prompt: "Which has a longer release?",
          a: { patch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.05, release: 0.2, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.05, release: 1.5, volume: 0.8 }, notes: ["C4"] },
          correct: "b" },
        { id: "1-4.1-4-5.q3", type: "ab-compare", prompt: "Which is plucky?",
          a: { patch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.01, release: 0.2, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "triangle", filterFreq: 2000, attack: 0.8, release: 1.5, volume: 0.8 }, notes: ["C4"] },
          correct: "a" },
        { id: "1-4.1-4-5.q4", type: "play-melody", prompt: "Play C-E-G with a slow attack",
          patch: { waveform: "triangle", filterFreq: 3000, attack: 0.6, release: 1.0, volume: 0.7 },
          sequence: ["C4", "E4", "G4"] },
        { id: "1-4.1-4-5.q5", type: "multi-choice", prompt: "Long release sounds like…",
          question: "Holding a key with long release =",
          options: ["The note cuts immediately", "The note lingers and fades",
                    "The pitch drops", "Distortion"],
          correctIndex: 1 },
      ],
    },
  ],
};
