import type { SubLesson } from "../../types";

export const subLesson_1_5: SubLesson = {
  slug: "1-5",
  title: "Filter",
  blurb: "Cutoff = brightness. Sculpt the tone.",
  lessons: [
    {
      slug: "1-5-1",
      title: "Filter = Tone Control",
      exercises: [
        { id: "1-5.1-5-1.q1", type: "concept-slide", prompt: "Filter sweeps cutoff",
          visual: "filter-sweep", caption: "A lowpass filter lets lows through and cuts highs above the cutoff." },
        { id: "1-5.1-5-1.q2", type: "tap-to-hear", prompt: "Saw with cutoff sweeping up",
          patch: { waveform: "sawtooth", filterFreq: 800, attack: 0.05, release: 1.0, volume: 0.8 },
          notes: ["C3"], caption: "Listen as harmonics open up." },
        { id: "1-5.1-5-1.q3", type: "multi-choice", prompt: "What does cutoff do?",
          question: "Lowering the cutoff frequency makes the sound…",
          options: ["Brighter", "Darker", "Louder", "Higher pitched"], correctIndex: 1 },
      ],
    },
    {
      slug: "1-5-2",
      title: "Cutoff = Brightness",
      exercises: [
        { id: "1-5.1-5-2.q1", type: "concept-slide", prompt: "Bright vs dark",
          visual: "filter-sweep", caption: "High cutoff = bright. Low cutoff = dark." },
        { id: "1-5.1-5-2.q2", type: "ab-compare", prompt: "Which is darker?",
          a: { patch: { waveform: "sawtooth", filterFreq: 600, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "sawtooth", filterFreq: 6000, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          correct: "a" },
        { id: "1-5.1-5-2.q3", type: "knob-tweak", prompt: "Set a low cutoff (~400 Hz) — make it dark",
          param: "filterFreq", target: 400, tolerance: 100,
          initialPatch: { waveform: "sawtooth", filterFreq: 5000, attack: 0.05, release: 0.5, volume: 0.8 },
          previewNote: "C4" },
        { id: "1-5.1-5-2.q4", type: "knob-tweak", prompt: "Set a high cutoff (~8000 Hz) — make it bright",
          param: "filterFreq", target: 8000, tolerance: 1500,
          initialPatch: { waveform: "sawtooth", filterFreq: 500, attack: 0.05, release: 0.5, volume: 0.8 },
          previewNote: "C4" },
      ],
    },
    {
      slug: "1-5-3",
      title: "Lowpass on Each Wave",
      exercises: [
        { id: "1-5.1-5-3.q1", type: "tap-to-hear", prompt: "Saw with cutoff at 800 Hz",
          patch: { waveform: "sawtooth", filterFreq: 800, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
        { id: "1-5.1-5-3.q2", type: "ab-compare", prompt: "Which is the saw filtered down?",
          a: { patch: { waveform: "sawtooth", filterFreq: 8000, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "sawtooth", filterFreq: 600, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          correct: "b" },
        { id: "1-5.1-5-3.q3", type: "ab-compare", prompt: "Which is the square filtered down?",
          a: { patch: { waveform: "square", filterFreq: 8000, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "square", filterFreq: 500, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          correct: "b" },
        { id: "1-5.1-5-3.q4", type: "multi-choice", prompt: "A heavily filtered saw sounds closest to…",
          question: "A saw with very low cutoff begins to sound like…",
          options: ["A square", "A sine", "A triangle", "A higher saw"],
          correctIndex: 1, explainer: "All the buzzy harmonics get cut, leaving mostly the fundamental." },
      ],
    },
    {
      slug: "1-5-4",
      title: "Make it Dark / Bright",
      exercises: [
        { id: "1-5.1-5-4.q1", type: "knob-tweak", prompt: "Make it dark — cutoff ~300 Hz",
          param: "filterFreq", target: 300, tolerance: 80,
          initialPatch: { waveform: "sawtooth", filterFreq: 5000, attack: 0.05, release: 0.5, volume: 0.8 },
          previewNote: "C4" },
        { id: "1-5.1-5-4.q2", type: "knob-tweak", prompt: "Make it bright — cutoff ~6000 Hz",
          param: "filterFreq", target: 6000, tolerance: 1200,
          initialPatch: { waveform: "sawtooth", filterFreq: 400, attack: 0.05, release: 0.5, volume: 0.8 },
          previewNote: "C4" },
        { id: "1-5.1-5-4.q3", type: "ab-compare", prompt: "Which is brighter?",
          a: { patch: { waveform: "sawtooth", filterFreq: 1500, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "sawtooth", filterFreq: 5000, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          correct: "b" },
        { id: "1-5.1-5-4.q4", type: "play-melody", prompt: "Play C-E-G with a filtered saw",
          patch: { waveform: "sawtooth", filterFreq: 1500, attack: 0.05, release: 0.5, volume: 0.8 },
          sequence: ["C4", "E4", "G4"] },
      ],
    },
    {
      slug: "1-5-5",
      title: "Filter Ear",
      exercises: [
        { id: "1-5.1-5-5.q1", type: "ab-compare", prompt: "Which is brighter?",
          a: { patch: { waveform: "sawtooth", filterFreq: 800, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          correct: "b" },
        { id: "1-5.1-5-5.q2", type: "ab-compare", prompt: "Which is darker?",
          a: { patch: { waveform: "square", filterFreq: 5000, attack: 0.05, release: 0.5, volume: 0.7 }, notes: ["C4"] },
          b: { patch: { waveform: "square", filterFreq: 800, attack: 0.05, release: 0.5, volume: 0.7 }, notes: ["C4"] },
          correct: "b" },
        { id: "1-5.1-5-5.q3", type: "ab-compare", prompt: "Which has more harmonics letting through?",
          a: { patch: { waveform: "sawtooth", filterFreq: 600, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          b: { patch: { waveform: "sawtooth", filterFreq: 4500, attack: 0.05, release: 0.5, volume: 0.8 }, notes: ["C4"] },
          correct: "b" },
        { id: "1-5.1-5-5.q4", type: "multi-choice", prompt: "Cutoff frequency is measured in…",
          question: "Filter cutoff is in…",
          options: ["Decibels (dB)", "Hertz (Hz)", "Seconds (s)", "Cents"], correctIndex: 1 },
      ],
    },
  ],
};
