import type { SubLesson } from "../../types";

export const subLesson_1_6: SubLesson = {
  slug: "1-6",
  title: "Polish",
  blurb: "Volume, reverb, sustain, octave — the small stuff that matters.",
  lessons: [
    {
      slug: "1-6-1",
      title: "Volume",
      exercises: [
        { id: "1-6.1-6-1.q1", type: "concept-slide", prompt: "Master volume",
          visual: "amplitude-vs-frequency", caption: "How loud the synth comes out overall." },
        { id: "1-6.1-6-1.q2", type: "knob-tweak", prompt: "Set a moderate volume (~0.5)",
          param: "volume", target: 0.5, tolerance: 0.08,
          initialPatch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.05, release: 0.5, volume: 0.1 },
          previewNote: "C4" },
        { id: "1-6.1-6-1.q3", type: "knob-tweak", prompt: "Set a louder volume (~0.9)",
          param: "volume", target: 0.9, tolerance: 0.08,
          initialPatch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.05, release: 0.5, volume: 0.2 },
          previewNote: "C4" },
        { id: "1-6.1-6-1.q4", type: "multi-choice", prompt: "Volume controls…",
          question: "Master volume affects…",
          options: ["Pitch", "Output amplitude", "Filter cutoff", "Attack time"],
          correctIndex: 1 },
      ],
    },
    {
      slug: "1-6-2",
      title: "Reverb On / Off",
      exercises: [
        { id: "1-6.1-6-2.q1", type: "concept-slide", prompt: "Reverb adds space",
          visual: "envelope-shape", caption: "Reverb simulates the sound bouncing around a room." },
        { id: "1-6.1-6-2.q2", type: "ab-compare", prompt: "Which has reverb?",
          a: { patch: { waveform: "triangle", filterFreq: 3000, attack: 0.05, release: 0.5, volume: 0.7, reverb: false }, notes: ["C4"] },
          b: { patch: { waveform: "triangle", filterFreq: 3000, attack: 0.05, release: 0.5, volume: 0.7, reverb: true }, notes: ["C4"] },
          correct: "b" },
        { id: "1-6.1-6-2.q3", type: "multi-choice", prompt: "Reverb makes a sound feel…",
          question: "What does reverb add?",
          options: ["More bass", "A sense of space / room", "Faster attack", "Higher pitch"],
          correctIndex: 1 },
      ],
    },
    {
      slug: "1-6-3",
      title: "Sustain Pedal",
      exercises: [
        { id: "1-6.1-6-3.q1", type: "concept-slide", prompt: "Sustain holds notes after you let go",
          visual: "envelope-shape", caption: "A sustain pedal keeps notes ringing even after you lift your finger." },
        { id: "1-6.1-6-3.q2", type: "play-melody", prompt: "Play C-E-G with a long release (sustain feel)",
          patch: { waveform: "triangle", filterFreq: 3000, attack: 0.05, release: 2.0, volume: 0.7 },
          sequence: ["C4", "E4", "G4"] },
        { id: "1-6.1-6-3.q3", type: "play-melody", prompt: "Play C-E-G short and snappy (no sustain)",
          patch: { waveform: "sawtooth", filterFreq: 4000, attack: 0.01, release: 0.1, volume: 0.7 },
          sequence: ["C4", "E4", "G4"] },
        { id: "1-6.1-6-3.q4", type: "multi-choice", prompt: "Sustain pedal effect:",
          question: "When sustain is on…",
          options: ["Notes cut off immediately", "Notes ring even after you release them",
                    "The pitch drops", "Volume goes up"],
          correctIndex: 1 },
      ],
    },
    {
      slug: "1-6-4",
      title: "Octave Shift",
      exercises: [
        { id: "1-6.1-6-4.q1", type: "concept-slide", prompt: "Octave shift moves the keyboard",
          visual: "octave-keyboard", caption: "Same note names, different range." },
        { id: "1-6.1-6-4.q2", type: "ab-compare", prompt: "Which is the higher octave?",
          a: { patch: { waveform: "triangle", filterFreq: 4000, volume: 0.7 }, notes: ["C3"] },
          b: { patch: { waveform: "triangle", filterFreq: 4000, volume: 0.7 }, notes: ["C5"] },
          correct: "b" },
        { id: "1-6.1-6-4.q3", type: "play-melody", prompt: "Play C across octaves",
          patch: { waveform: "triangle", filterFreq: 4000, volume: 0.7 },
          sequence: ["C3", "C4", "C5"] },
      ],
    },
  ],
};
