import type { SubLesson } from "../../types";

export const subLesson_1_7: SubLesson = {
  slug: "1-7",
  title: "Synth 1 Pro Mastery",
  blurb: "Recreate iconic sounds, then play freely.",
  lessons: [
    {
      slug: "1-7-1",
      title: "Recreate a Pluck",
      exercises: [
        { id: "1-7.1-7-1.q1", type: "knob-tweak", prompt: "Cutoff ~2000 Hz",
          param: "filterFreq", target: 2000, tolerance: 400,
          initialPatch: { waveform: "sawtooth", filterFreq: 8000, attack: 1.0, release: 1.0, volume: 0.8 },
          previewNote: "C4" },
        { id: "1-7.1-7-1.q2", type: "knob-tweak", prompt: "Fast attack (0.01 s)",
          param: "attack", target: 0.01, tolerance: 0.05,
          initialPatch: { waveform: "sawtooth", filterFreq: 2000, attack: 1.0, release: 1.0, volume: 0.8 },
          previewNote: "C4" },
        { id: "1-7.1-7-1.q3", type: "knob-tweak", prompt: "Short release (~0.3 s)",
          param: "release", target: 0.3, tolerance: 0.15,
          initialPatch: { waveform: "sawtooth", filterFreq: 2000, attack: 0.01, release: 1.5, volume: 0.8 },
          previewNote: "C4" },
        { id: "1-7.1-7-1.q4", type: "play-melody", prompt: "Play your pluck: C-E-G",
          patch: { waveform: "sawtooth", filterFreq: 2000, attack: 0.01, release: 0.3, volume: 0.8 },
          sequence: ["C4", "E4", "G4"] },
      ],
    },
    {
      slug: "1-7-2",
      title: "Recreate a Pad",
      exercises: [
        { id: "1-7.1-7-2.q1", type: "knob-tweak", prompt: "Cutoff ~1500 Hz",
          param: "filterFreq", target: 1500, tolerance: 350,
          initialPatch: { waveform: "triangle", filterFreq: 5000, attack: 0.01, release: 0.5, volume: 0.7 },
          previewNote: "C4" },
        { id: "1-7.1-7-2.q2", type: "knob-tweak", prompt: "Slow attack (~1.5 s)",
          param: "attack", target: 1.5, tolerance: 0.4,
          initialPatch: { waveform: "triangle", filterFreq: 1500, attack: 0.01, release: 0.5, volume: 0.7 },
          previewNote: "C4" },
        { id: "1-7.1-7-2.q3", type: "knob-tweak", prompt: "Long release (~2 s)",
          param: "release", target: 2.0, tolerance: 0.4,
          initialPatch: { waveform: "triangle", filterFreq: 1500, attack: 1.5, release: 0.2, volume: 0.7 },
          previewNote: "C4" },
        { id: "1-7.1-7-2.q4", type: "play-melody", prompt: "Play your pad: C-E-G",
          patch: { waveform: "triangle", filterFreq: 1500, attack: 1.5, release: 2.0, volume: 0.7, reverb: true },
          sequence: ["C4", "E4", "G4"] },
      ],
    },
    {
      slug: "1-7-3",
      title: "Recreate a Lead",
      exercises: [
        { id: "1-7.1-7-3.q1", type: "knob-tweak", prompt: "Cutoff ~4000 Hz",
          param: "filterFreq", target: 4000, tolerance: 700,
          initialPatch: { waveform: "square", filterFreq: 1000, attack: 0.05, release: 0.4, volume: 0.7 },
          previewNote: "C4" },
        { id: "1-7.1-7-3.q2", type: "knob-tweak", prompt: "Quick attack (0.05 s)",
          param: "attack", target: 0.05, tolerance: 0.05,
          initialPatch: { waveform: "square", filterFreq: 4000, attack: 1.0, release: 0.4, volume: 0.7 },
          previewNote: "C4" },
        { id: "1-7.1-7-3.q3", type: "knob-tweak", prompt: "Medium release (~0.4 s)",
          param: "release", target: 0.4, tolerance: 0.15,
          initialPatch: { waveform: "square", filterFreq: 4000, attack: 0.05, release: 1.5, volume: 0.7 },
          previewNote: "C4" },
        { id: "1-7.1-7-3.q4", type: "play-melody", prompt: "Play your lead: C-E-G-A",
          patch: { waveform: "square", filterFreq: 4000, attack: 0.05, release: 0.4, volume: 0.7 },
          sequence: ["C4", "E4", "G4", "A4"] },
      ],
    },
    {
      slug: "1-7-4",
      title: "Free Sound Design",
      exercises: [
        { id: "1-7.1-7-4.q1", type: "free-play", prompt: "Design any sound, then play a tune",
          durationS: 60, caption: "60 seconds. Try every knob." },
      ],
    },
    {
      slug: "1-7-5",
      title: "Free Play",
      exercises: [
        { id: "1-7.1-7-5.q1", type: "free-play", prompt: "Go wild — no timer, no goal",
          caption: "You've earned this." },
      ],
    },
  ],
};
